name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 设置为您项目的主分支
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 设置为您项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          rm -rf .git
          git init
          git remote add origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/shenghuo2/shenghuo2.github.io.git
          if git fetch origin gh-pages; then
            git checkout -b gh-pages origin/gh-pages
          else
            git checkout --orphan gh-pages
          fi
          rsync -av --delete ./dist/ ./ || (echo "Rsync had some issues, but continuing..." && true)
          git add .
          git commit -m "Deploy to GitHub Pages" || true
          git push -u origin gh-pages
